<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InformasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('informasi')->insert([
            [
                'id_kategori' => 1,
                'judul_informasi' => 'Wisata Bukit Kapur Arosbaya',
                'isi_informasi' => '<h1>Judul Berita Utama</h1><p><strong>Penulis:</strong> Nama Penulis</p><p><strong>Tanggal:</strong> 28 Agustus 2024</p><p class="ql-indent-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non urna nec dolor euismod malesuada. Duis aliquet arcu in libero sodales, eu gravida est vestibulum.</p><p><img src="gambar-berita.jpg" alt="Gambar Berita">Deskripsi gambar berita</p><p><em>Curabitur pretium erat</em> </p><p><u>ac massa dictum,</u> </p><p><s>nec lobortis elit vulputate</s>. </p><p class="ql-align-center">Maecenas bibendum orci in lacus suscipit blandit. Integer euismod dui sit amet ex facilisis bibendum. Nam vel orci sit amet lorem auctor dapibus non nec dolor.</p><blockquote>"Ini adalah kutipan penting dari berita yang ingin disorot. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."</blockquote><blockquote>- Nama Sumber</blockquote><p>Aenean a arcu et urna vestibulum gravida. Donec vehicula odio id mi facilisis, et vehicula quam tincidunt. Nam luctus, est sed dapibus feugiat, elit velit varius risus, eget lacinia tortor elit sit amet dolor.</p><h2>Subjudul Berita</h2><p>Quisque gravida felis at nisi aliquet volutpat. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur ac justo nec arcu varius fermentum non a arcu.</p><ol><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting pertama berita</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting kedua berita</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting ketiga berita</li></ol><p>Aliquam erat volutpat. Nam iaculis neque et tortor vulputate, ac fringilla dolor dictum. Integer nec erat id urna tempor congue non nec justo.</p><p><strong>Kategori:</strong> Kategori Berita</p><p><strong>Tags:</strong> <a href="#" rel="noopener noreferrer" target="_blank">Tag1</a>, <a href="#" rel="noopener noreferrer" target="_blank">Tag2</a>, <a href="#" rel="noopener noreferrer" target="_blank">Tag3</a></p>',
                'gambar_informasi' => 'informasis/8NoEfx4ms57mp2ujjrtdJQlEzZcOXv502gxZvp5R.png',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_kategori' => 2,
                'judul_informasi' => 'Kuliner Sate Madura',
                'isi_informasi' => '<h1>Judul Berita Utama</h1><p><strong>Penulis:</strong> Nama Penulis</p><p><strong>Tanggal:</strong> 28 Agustus 2024</p><p class="ql-indent-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non urna nec dolor euismod malesuada. Duis aliquet arcu in libero sodales, eu gravida est vestibulum.</p><p><img src="gambar-berita.jpg" alt="Gambar Berita">Deskripsi gambar berita</p><p><em>Curabitur pretium erat</em> </p><p><u>ac massa dictum,</u> </p><p><s>nec lobortis elit vulputate</s>. </p><p class="ql-align-center">Maecenas bibendum orci in lacus suscipit blandit. Integer euismod dui sit amet ex facilisis bibendum. Nam vel orci sit amet lorem auctor dapibus non nec dolor.</p><blockquote>"Ini adalah kutipan penting dari berita yang ingin disorot. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."</blockquote><blockquote>- Nama Sumber</blockquote><p>Aenean a arcu et urna vestibulum gravida. Donec vehicula odio id mi facilisis, et vehicula quam tincidunt. Nam luctus, est sed dapibus feugiat, elit velit varius risus, eget lacinia tortor elit sit amet dolor.</p><h2>Subjudul Berita</h2><p>Quisque gravida felis at nisi aliquet volutpat. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur ac justo nec arcu varius fermentum non a arcu.</p><ol><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting pertama berita</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting kedua berita</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting ketiga berita</li></ol><p>Aliquam erat volutpat. Nam iaculis neque et tortor vulputate, ac fringilla dolor dictum. Integer nec erat id urna tempor congue non nec justo.</p><p><strong>Kategori:</strong> Kategori Berita</p><p><strong>Tags:</strong> <a href="#" rel="noopener noreferrer" target="_blank">Tag1</a>, <a href="#" rel="noopener noreferrer" target="_blank">Tag2</a>, <a href="#" rel="noopener noreferrer" target="_blank">Tag3</a></p>',
                'gambar_informasi' => 'informasis/8NoEfx4ms57mp2ujjrtdJQlEzZcOXv502gxZvp5R.png',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_kategori' => 2,
                'judul_informasi' => 'Kuliner Sate Madura',
                'isi_informasi' => '<h1>Judul Berita Utama</h1><p><strong>Penulis:</strong> Nama Penulis</p><p><strong>Tanggal:</strong> 28 Agustus 2024</p><p class="ql-indent-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non urna nec dolor euismod malesuada. Duis aliquet arcu in libero sodales, eu gravida est vestibulum.</p><p><img src="gambar-berita.jpg" alt="Gambar Berita">Deskripsi gambar berita</p><p><em>Curabitur pretium erat</em> </p><p><u>ac massa dictum,</u> </p><p><s>nec lobortis elit vulputate</s>. </p><p class="ql-align-center">Maecenas bibendum orci in lacus suscipit blandit. Integer euismod dui sit amet ex facilisis bibendum. Nam vel orci sit amet lorem auctor dapibus non nec dolor.</p><blockquote>"Ini adalah kutipan penting dari berita yang ingin disorot. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."</blockquote><blockquote>- Nama Sumber</blockquote><p>Aenean a arcu et urna vestibulum gravida. Donec vehicula odio id mi facilisis, et vehicula quam tincidunt. Nam luctus, est sed dapibus feugiat, elit velit varius risus, eget lacinia tortor elit sit amet dolor.</p><h2>Subjudul Berita</h2><p>Quisque gravida felis at nisi aliquet volutpat. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur ac justo nec arcu varius fermentum non a arcu.</p><ol><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting pertama berita</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting kedua berita</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting ketiga berita</li></ol><p>Aliquam erat volutpat. Nam iaculis neque et tortor vulputate, ac fringilla dolor dictum. Integer nec erat id urna tempor congue non nec justo.</p><p><strong>Kategori:</strong> Kategori Berita</p><p><strong>Tags:</strong> <a href="#" rel="noopener noreferrer" target="_blank">Tag1</a>, <a href="#" rel="noopener noreferrer" target="_blank">Tag2</a>, <a href="#" rel="noopener noreferrer" target="_blank">Tag3</a></p>',
                'gambar_informasi' => 'informasis/8NoEfx4ms57mp2ujjrtdJQlEzZcOXv502gxZvp5R.png',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_kategori' => 1,
                'judul_informasi' => 'Wisata Bukit Kapur Arosbaya',
                'isi_informasi' => '<h1>Judul Berita Utama</h1><p><strong>Penulis:</strong> Nama Penulis</p><p><strong>Tanggal:</strong> 28 Agustus 2024</p><p class="ql-indent-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non urna nec dolor euismod malesuada. Duis aliquet arcu in libero sodales, eu gravida est vestibulum.</p><p><img src="gambar-berita.jpg" alt="Gambar Berita">Deskripsi gambar berita</p><p><em>Curabitur pretium erat</em> </p><p><u>ac massa dictum,</u> </p><p><s>nec lobortis elit vulputate</s>. </p><p class="ql-align-center">Maecenas bibendum orci in lacus suscipit blandit. Integer euismod dui sit amet ex facilisis bibendum. Nam vel orci sit amet lorem auctor dapibus non nec dolor.</p><blockquote>"Ini adalah kutipan penting dari berita yang ingin disorot. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."</blockquote><blockquote>- Nama Sumber</blockquote><p>Aenean a arcu et urna vestibulum gravida. Donec vehicula odio id mi facilisis, et vehicula quam tincidunt. Nam luctus, est sed dapibus feugiat, elit velit varius risus, eget lacinia tortor elit sit amet dolor.</p><h2>Subjudul Berita</h2><p>Quisque gravida felis at nisi aliquet volutpat. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur ac justo nec arcu varius fermentum non a arcu.</p><ol><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting pertama berita</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting kedua berita</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting ketiga berita</li></ol><p>Aliquam erat volutpat. Nam iaculis neque et tortor vulputate, ac fringilla dolor dictum. Integer nec erat id urna tempor congue non nec justo.</p><p><strong>Kategori:</strong> Kategori Berita</p><p><strong>Tags:</strong> <a href="#" rel="noopener noreferrer" target="_blank">Tag1</a>, <a href="#" rel="noopener noreferrer" target="_blank">Tag2</a>, <a href="#" rel="noopener noreferrer" target="_blank">Tag3</a></p>',
                'gambar_informasi' => 'informasis/8NoEfx4ms57mp2ujjrtdJQlEzZcOXv502gxZvp5R.png',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_kategori' => 1,
                'judul_informasi' => 'Wisata Bukit Kapur Arosbaya',
                'isi_informasi' => '<h1>Judul Berita Utama</h1><p><strong>Penulis:</strong> Nama Penulis</p><p><strong>Tanggal:</strong> 28 Agustus 2024</p><p class="ql-indent-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non urna nec dolor euismod malesuada. Duis aliquet arcu in libero sodales, eu gravida est vestibulum.</p><p><img src="gambar-berita.jpg" alt="Gambar Berita">Deskripsi gambar berita</p><p><em>Curabitur pretium erat</em> </p><p><u>ac massa dictum,</u> </p><p><s>nec lobortis elit vulputate</s>. </p><p class="ql-align-center">Maecenas bibendum orci in lacus suscipit blandit. Integer euismod dui sit amet ex facilisis bibendum. Nam vel orci sit amet lorem auctor dapibus non nec dolor.</p><blockquote>"Ini adalah kutipan penting dari berita yang ingin disorot. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."</blockquote><blockquote>- Nama Sumber</blockquote><p>Aenean a arcu et urna vestibulum gravida. Donec vehicula odio id mi facilisis, et vehicula quam tincidunt. Nam luctus, est sed dapibus feugiat, elit velit varius risus, eget lacinia tortor elit sit amet dolor.</p><h2>Subjudul Berita</h2><p>Quisque gravida felis at nisi aliquet volutpat. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur ac justo nec arcu varius fermentum non a arcu.</p><ol><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting pertama berita</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting kedua berita</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting ketiga berita</li></ol><p>Aliquam erat volutpat. Nam iaculis neque et tortor vulputate, ac fringilla dolor dictum. Integer nec erat id urna tempor congue non nec justo.</p><p><strong>Kategori:</strong> Kategori Berita</p><p><strong>Tags:</strong> <a href="#" rel="noopener noreferrer" target="_blank">Tag1</a>, <a href="#" rel="noopener noreferrer" target="_blank">Tag2</a>, <a href="#" rel="noopener noreferrer" target="_blank">Tag3</a></p>',
                'gambar_informasi' => 'informasis/8NoEfx4ms57mp2ujjrtdJQlEzZcOXv502gxZvp5R.png',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_kategori' => 1,
                'judul_informasi' => 'Wisata Bukit Kapur Arosbaya',
                'isi_informasi' => '<h1>Judul Berita Utama</h1><p><strong>Penulis:</strong> Nama Penulis</p><p><strong>Tanggal:</strong> 28 Agustus 2024</p><p class="ql-indent-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non urna nec dolor euismod malesuada. Duis aliquet arcu in libero sodales, eu gravida est vestibulum.</p><p><img src="gambar-berita.jpg" alt="Gambar Berita">Deskripsi gambar berita</p><p><em>Curabitur pretium erat</em> </p><p><u>ac massa dictum,</u> </p><p><s>nec lobortis elit vulputate</s>. </p><p class="ql-align-center">Maecenas bibendum orci in lacus suscipit blandit. Integer euismod dui sit amet ex facilisis bibendum. Nam vel orci sit amet lorem auctor dapibus non nec dolor.</p><blockquote>"Ini adalah kutipan penting dari berita yang ingin disorot. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."</blockquote><blockquote>- Nama Sumber</blockquote><p>Aenean a arcu et urna vestibulum gravida. Donec vehicula odio id mi facilisis, et vehicula quam tincidunt. Nam luctus, est sed dapibus feugiat, elit velit varius risus, eget lacinia tortor elit sit amet dolor.</p><h2>Subjudul Berita</h2><p>Quisque gravida felis at nisi aliquet volutpat. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur ac justo nec arcu varius fermentum non a arcu.</p><ol><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting pertama berita</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting kedua berita</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting ketiga berita</li></ol><p>Aliquam erat volutpat. Nam iaculis neque et tortor vulputate, ac fringilla dolor dictum. Integer nec erat id urna tempor congue non nec justo.</p><p><strong>Kategori:</strong> Kategori Berita</p><p><strong>Tags:</strong> <a href="#" rel="noopener noreferrer" target="_blank">Tag1</a>, <a href="#" rel="noopener noreferrer" target="_blank">Tag2</a>, <a href="#" rel="noopener noreferrer" target="_blank">Tag3</a></p>',
                'gambar_informasi' => 'informasis/8NoEfx4ms57mp2ujjrtdJQlEzZcOXv502gxZvp5R.png',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id_kategori' => 1,
                'judul_informasi' => 'Wisata Bukit Kapur Arosbaya',
                'isi_informasi' => '<h1>Judul Berita Utama</h1><p><strong>Penulis:</strong> Nama Penulis</p><p><strong>Tanggal:</strong> 28 Agustus 2024</p><p class="ql-indent-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non urna nec dolor euismod malesuada. Duis aliquet arcu in libero sodales, eu gravida est vestibulum.</p><p><img src="gambar-berita.jpg" alt="Gambar Berita">Deskripsi gambar berita</p><p><em>Curabitur pretium erat</em> </p><p><u>ac massa dictum,</u> </p><p><s>nec lobortis elit vulputate</s>. </p><p class="ql-align-center">Maecenas bibendum orci in lacus suscipit blandit. Integer euismod dui sit amet ex facilisis bibendum. Nam vel orci sit amet lorem auctor dapibus non nec dolor.</p><blockquote>"Ini adalah kutipan penting dari berita yang ingin disorot. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."</blockquote><blockquote>- Nama Sumber</blockquote><p>Aenean a arcu et urna vestibulum gravida. Donec vehicula odio id mi facilisis, et vehicula quam tincidunt. Nam luctus, est sed dapibus feugiat, elit velit varius risus, eget lacinia tortor elit sit amet dolor.</p><h2>Subjudul Berita</h2><p>Quisque gravida felis at nisi aliquet volutpat. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur ac justo nec arcu varius fermentum non a arcu.</p><ol><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting pertama berita</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting kedua berita</li><li data-list="bullet"><span class="ql-ui" contenteditable="false"></span>Poin penting ketiga berita</li></ol><p>Aliquam erat volutpat. Nam iaculis neque et tortor vulputate, ac fringilla dolor dictum. Integer nec erat id urna tempor congue non nec justo.</p><p><strong>Kategori:</strong> Kategori Berita</p><p><strong>Tags:</strong> <a href="#" rel="noopener noreferrer" target="_blank">Tag1</a>, <a href="#" rel="noopener noreferrer" target="_blank">Tag2</a>, <a href="#" rel="noopener noreferrer" target="_blank">Tag3</a></p>',
                'gambar_informasi' => 'informasis/8NoEfx4ms57mp2ujjrtdJQlEzZcOXv502gxZvp5R.png',
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);
    }
}
